FROM python:3.10-buster as build
ENV UVICORN_PORT 5000
ENV UVICORN_HOST 0.0.0.0
ENV FLIT_ROOT_INSTALL 1

RUN mkdir -p /opt/flightsapi
WORKDIR /opt/flightsapi

COPY . .
RUN pip install --no-cache-dir --upgrade pip && pip install --no-cache-dir flit && flit build
EXPOSE 5000
RUN pip install dist/*whl

CMD uvicorn flightsapi:app
